---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Deploys a route table.

Parameters:
  Subnet:
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id

  IGW:
    Type: String

Resources:
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet

  InternetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref RouteTable

Outputs:
  RouteTable:
    Value: !Ref RouteTable
